/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>





#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  //#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
#if 0
	// Addition of two numbers
	__asm volatile("LDR R1,= #0x20001000");
	__asm volatile("LDR R2,= #0x20001004");
	__asm volatile("LDR R3,[R1]");
	__asm volatile("LDR R4,[R2]");
	__asm volatile("ADD R5,R3,R4");
	__asm volatile("STR R5,[R3]");
#endif

#if 0
	//input
	int val=13;
	__asm volatile("MOV R0,%0"::"i"(50));
#endif

#if 0
	//output
	uint32_t control_reg;
	__asm volatile("MRS %0,CONTROL":"=r"(control_reg));
#endif

#if 0
	//Swapping the value
	uint32_t val1=29;
	uint32_t val2=7;
		__asm volatile("MOV %0,%1":"=r"(val1):"r"(val2));
#endif

#if 0
		int p1, *p2;
		p2=(int *)0x20000004;
		__asm volatile("LDR %0,[%1]":"=r"(p1):"r"(p2));
#endif


    /* Loop forever */
	for(;;);
}
