/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void generate_interrupt()
{
   uint32_t *pSTIR=(uint32_t *)0xE000EF00;
   uint32_t *pISER0=(uint32_t *)0xE000E100;
   /* 1. These are some are Cortex M4 Processor system control register which can only be accessed in priviliged access level.
    * 2. Any attempt to change the contents of these register from being in unpreviliged acces level will cause the processor fault exception
    */

//Enable IRQ3
   *pISER0 |=(1<<3);

//generate an interrupt from software for IRQ3
   *pSTIR=(3&0x1FF);
}
void AccessSwitch_1()
{
	__asm volatile("MRS R0,CONTROL");
	__asm volatile("ORR R0,R0,#0x01");
	__asm volatile("MSR CONTROL,R0");


}
void AccessSwitch_0()
{
	__asm volatile("MRS R0,CONTROL");
	__asm volatile("ORR R0,R0,#1");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("CPS #0x10");
	//__asm volatile("AND R0,R0,#0xFFFFFFFE");



}
void RTC_WKUP_IRQHandler(void)
{
   printf("I'm in Handler Mode\n");
}
void HardFault(void)
{
	printf("I am in thread mode : ASR");
}

int main(void)
{
	printf("I,m in thread mode : Before interrupts\n");
	AccessSwitch_1();
	AccessSwitch_0();
	generate_interrupt();
	printf("I,m in thread mode : After interrupts\n");
    /* Loop forever */
	for(;;);
}


